apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: flyingfish-python 
  janus-idp.io/tekton: flyingfish-python
  backstage.io/kubernetes-id: flyingfish-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: flyingfish-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  